image: python:3.7-slim-buster
 
before_script:
- python -V # Print out python version for debugging
- pip install .[extras]
 
stages:
- test
 
test_job:
  stage: test
  script:
  - echo "Running tests"
  - python -m unittest discover -s "./tests/"