channels:
  - conda-forge
dependencies:
  - black
  - darglint
  - deptry
  - doc8
  - flake8
  - flake8-annotations
  - flake8-black
  - flake8-bugbear
  - flake8-docstrings
  - flake8-import-order
  - furo
  - isort
  - mypy
  - nox
  - pip
  - pytest
  - pytest-cov
  - python>=3.10
  - rstcheck
  - sphinx
  - sphinx-copybutton
  - sphinx-inline-tabs
  - sphinxcontrib-bibtex
  - types-setuptools
